#define NAMESPACE_RENDERINENGINE_BEGIN namespace BAMS { namespace RENDERINENGINE {
#define NAMESPACE_RENDERINENGINE_END } }
#define NAMESPACE_RENDERINENGINE BAMS::RENDERINENGINE

#define RE_EXPORT BAMS_EXPORT

NAMESPACE_RENDERINENGINE_BEGIN

#include "RenderingEngine_Config.h"
#include "RenderingEngine_VertexDescription.h"


NAMESPACE_RENDERINENGINE_END

