#define NAMESPACE_RENDERINENGINE_BEGIN namespace BAMS { namespace RENDERINENGINE {
#define NAMESPACE_RENDERINENGINE_END } }
#define NAMESPACE_RENDERINENGINE BAMS::RENDERINENGINE

NAMESPACE_RENDERINENGINE_BEGIN

#include "RenderingEngine_Config.h"

NAMESPACE_RENDERINENGINE_END